include:
  - project: muni-kypo-images/ci-cd-virtual-images
    file: qemu.yml

variables:
  NAME: "opnsense"
  TYPE: "linux"
  DISTRO: "freebsd"

build-qemu:
  before_script:
    - if [ ! -f opnsense.iso ]; then
    -  wget -nv https://mirror.dns-root.de/opnsense/releases/23.1/OPNsense-23.1-OpenSSL-dvd-amd64.iso.bz2 -O opnsense.iso.bz2
    -  bunzip2 opnsense.iso.bz2
    - fi
